name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - main  # 触发构建的分支，注意检查你本地初始化 Git 时默认分支是 main 还是 master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 授予推送 HTML 到 gh-pages 分支的权限

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # 云端使用的 Node 版本

    - name: Install Dependencies
      run: npm install

    - name: Build Hexo
      run: npx hexo generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages